Update Place Tomba Dougoula
whosonfirst-data/whosonfirst-data-admin-gn pull request #36
Opened 2023-12-06 22:29 UTC by nvkelso

Updating `data/126/021/452/3/1260214523.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

2023-12-06 22:31 UTC, nvkelso commented
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/2172

2023-12-06 23:16 UTC, 5212BABA approved these changes
Thank you very much for validating my suggestion by correcting erroneous names

2023-12-07 07:18 UTC, stepps00 commented on data/126/021/452/3/1260214523.geojson
> +    ],    "name:eng_x_variant":[
Hmm.. looks like invalid geojson? I also see an extra return char at the tail end of this record. If you're able to Exportify the record, this should correct itself..

2023-12-07 07:18 UTC, stepps00 requested changes
See Exportify coment

2023-12-07 18:51 UTC, nvkelso commented
Replaced with https://github.com/whosonfirst-data/whosonfirst-data-admin-gn/pull/41.

Back story here is I missed setting the English preferred name in the tool so edited that manually in GH.com interface, which then garbled up the formatting. Always better to use Write Field to recreate the work – or to pull it into local checkout and apply exportify manually.

2023-12-07 18:51 UTC, closed without merging