Update 1260214523.geojson
whosonfirst-data/whosonfirst-data-admin-gn pull request #39
Opened 2023-12-07 12:03 UTC by 5212BABA

@stepps00 @nvkelso il faut mes modifications si c est  valable

2023-12-07 19:07 UTC, nvkelso commented on data/126/021/452/3/1260214523.geojson
> +    "geom:bbox":"-10.18,11.73333,-10.18,11.73333",
NOTE: These `geom` properties are auto-generated. To change them you'd need to edit the `geometry` section below (which it looks like you did, good). Generally don't manually edit these...

2023-12-07 19:07 UTC, nvkelso commented on data/126/021/452/3/1260214523.geojson
> +    "gn:asciiname":"Tomba kanssa",
GeoNames (`gn` prefixed properties) shouldn't be modified, they preserve what GeoNames knew about the place when we imported it.

2023-12-07 19:09 UTC, nvkelso commented on data/126/021/452/3/1260214523.geojson
> +    "gn:feature_class":"A",
WOF uses "capital_of" properties to record these kind of things instead.

See also:

- https://github.com/whosonfirst/whosonfirst-properties/blob/main/properties/wof/capital_of.json
- Example: https://spelunker.whosonfirst.org/id/85922845/

2023-12-07 19:10 UTC, nvkelso commented on data/126/021/452/3/1260214523.geojson
> +    "gn:modification_date":"2023-12-07",
WOF exportify tool will generate a date in unix timestamp format for you automatically, but puts it in `wof:modified`.

2023-12-07 19:10 UTC, nvkelso commented on data/126/021/452/3/1260214523.geojson
> +    "wof:name":"Tomba kanssa",
Nit: capital K in `Tomba kanssa`.

2023-12-07 19:12 UTC, nvkelso requested changes
Since I merged my PR for this place in https://github.com/whosonfirst-data/whosonfirst-data-admin-gn/pull/41...

The only bit not captured that you could PR again (start over please versus updating this PR) is the changes in the geometry coordinate (and auto generated bbox and geom properties) and if you want to specify the admin capital status.

2024-03-26 20:26 UTC, stepps00 commented
I believe the record in this PR was updated separately to resolve some of these issues. @nvkelso @5212BABA are we OK to close this PR/branch?

2024-03-26 20:48 UTC, nvkelso commented
Yes, this PR can be closed.

If we wanted to do any follow ups, they are listed in https://github.com/whosonfirst-data/whosonfirst-data-admin-gn/pull/39#pullrequestreview-1770872205 but as rainy day.

2024-03-26 20:48 UTC, closed without merging